
export interface OfflineNote {
  id: string;
  title: string;
  topic: string;
  content: string; // Markdown content
}

export const offlineNotes: OfflineNote[] = [
  {
    id: 'os-notes',
    title: 'Operating Systems - Last Minute Notes',
    topic: 'Operating Systems',
    content: `
# Operating Systems - Quick Recap

## Types of Operating System (OS)
**Batch OS**
- Executes a set of similar jobs together.
- CPU processes one job at a time; next job starts only after the previous finishes.

**Multiprogramming OS**
- Multiple jobs are loaded in memory.
- CPU switches to another job when one is waiting (e.g., for I/O).
- Keeps CPU always busy.

**Time-Sharing / Multitasking OS**
- A type of multiprogramming where each process gets a fixed time slice (quantum).
- CPU switches between tasks quickly so all users/processes feel simultaneous execution.

**Multiprocessing OS**
- Uses more than one CPU for executing processes.
- Improves system throughput.

**Multi-user OS**
- Allows multiple users to work at the same time.
- Can run on single or multiple processors.

**Distributed OS**
- Manages a group of interconnected computers that communicate over a network.
- Each system has its own CPU and memory, but works as a single system.

**Network OS**
- Runs on a server to manage files, users, security, and applications over a network.
- Allows shared access to resources like printers and files.

**Real-Time OS (RTOS)**
- Designed for dedicated tasks with strict deadlines.
- Common in embedded systems, medical devices, and industrial machines.

## Threads
**Definition**: A thread is a lightweight process and the basic unit of CPU execution.
**Features**:
- Has its own program counter, registers, and stack.
- Shares code, data, files, and signals with other threads of the same process.
**Creation**: Using \`fork()\` system call.
- A process with n \`fork()\` calls creates 2^n - 1 child processes.

## CPU Scheduling Algorithms

**1. First Come First Serve (FCFS)**
- Simplest algorithm. Processes are attended in the order they arrive.
- **Non-preemptive**.
- Assign based on arrival time. Tie-break with process ID.
- Free from starvation.
- *Drawback*: Convoy effect (long waiting times if first job is long).

**2. Shortest Job First (SJF)**
- Selects the waiting process with the smallest execution time.
- **Non-preemptive**.
- Minimizes average response time.
- *Drawback*: Starvation possible. Requires knowing burst time in advance.

**3. Shortest Remaining Time First (SRTF)**
- Preemptive version of SJF.
- Schedules based on shortest **remaining** burst time.
- Minimizes average turnaround time.
- *Drawback*: Potential starvation for long processes.

**4. Round Robin (RR)**
- Preemptive FCFS with time quantum/slice.
- Best for time-sharing systems.
- *Quantum trade-off*: 
  - Too small = high context switch overhead.
  - Too large = behaves like FCFS.

**5. Priority Based Scheduling**
- Schedules based on priority (highest first).
- Can be **preemptive** or **non-preemptive**.
- *Drawback*: Starvation (solved by Aging).

**6. Highest Response Ratio Next (HRRN)**
- **Non-preemptive**.
- Schedules based on highest response ratio.
- Response Ratio = (Waiting Time + Burst Time) / Burst Time.
- Favors shorter jobs but prevents starvation for longer jobs (as waiting time increases, ratio increases).

## Deadlock
**Definition**: A situation where a set of processes are blocked because each process is holding a resource and waiting for another resource acquired by some other process.

**Necessary Conditions (Coffman Conditions)**:
1. **Mutual Exclusion**: At least one resource must be held in a non-shareable mode.
2. **Hold and Wait**: A process exists that is holding at least one resource and waiting for additional resources held by others.
3. **No Preemption**: Resources cannot be preempted; a resource can be released only voluntarily by the process holding it.
4. **Circular Wait**: A set of processes {P0, P1, ..., Pn} exists such that P0 is waiting for a resource held by P1, P1 for P2, ..., and Pn for P0.

**Deadlock Handling**:
- **Prevention**: Invalidate one of the 4 conditions.
- **Avoidance**: Banker's Algorithm (ensure system stays in a safe state).
- **Detection & Recovery**: Let it happen, then detect and resolve (kill process or preempt resource).
- **Ignorance**: (Ostrich Algorithm) Pretend it never happens (used by Windows/Unix mostly).

## Memory Management
**Goal**: Manage primary memory efficiently.
**Logical vs Physical Address**:
- *Logical*: Generated by CPU (Virtual address).
- *Physical*: Address seen by the memory unit.

**Paging**:
- Non-contiguous memory allocation.
- Divide physical memory into fixed-sized blocks (**frames**).
- Divide logical memory into blocks of same size (**pages**).
- Solves external fragmentation.

**Segmentation**:
- Divides memory into variable-sized segments (Code, Stack, Data, etc.).
- Closer to user's view of memory.

**Virtual Memory**:
- allows execution of processes not completely in memory.
- **Demand Paging**: Bring pages into memory only when needed (page fault).
- **Page Replacement Algorithms**: FIFO, LRU (Least Recently Used), Optimal.
`
  },
  {
    id: 'cn-notes',
    title: 'Computer Networks - Quick Recap',
    topic: 'Computer Networks',
    content: `
# Computer Networks - Quick Recap

## OSI Model Layers (Please Do Not Touch Steve's Pet Alligator)
1. **Physical**: Bits transmission (Cables, Hubs).
2. **Data Link**: Frames, MAC addressing, Error detection (Switch, Bridge).
3. **Network**: Packets, IP addressing, Routing (Routers).
4. **Transport**: Segments, TCP/UDP, End-to-end delivery.
5. **Session**: Session management, Dialog control.
6. **Presentation**: Formatting, Encryption, Compression.
7. **Application**: Network services for apps (HTTP, FTP, SMTP).

## TCP vs UDP
| Feature | TCP (Transmission Control Protocol) | UDP (User Datagram Protocol) |
|---------|-----------------------------------|----------------------------|
| Type | Connection-oriented | Connection-less |
| Reliability | Reliable (Ack, Retransmission) | Unreliable (Fire and forget) |
| Order | Ordered delivery | Unordered |
| Speed | Slower | Faster |
| Usage | Web, Email, File Transfer | Streaming, Gaming, DNS, VoIP |

## IP Addressing
**IPv4**: 32-bit address (e.g., 192.168.1.1).
**IPv6**: 128-bit address (Hexadecimal).

**Classes**:
- Class A: 0 - 127 (Unary 0)
- Class B: 128 - 191 (Unary 10)
- Class C: 192 - 223 (Unary 110)
- Class D: 224 - 239 (Multicast)
- Class E: 240 - 255 (Research)

## Common Protocols
- **HTTP/HTTPS**: HyperText Transfer Protocol (Port 80/443).
- **FTP**: File Transfer Protocol (Port 20/21).
- **SMTP**: Simple Mail Transfer Protocol (Port 25) - Sending email.
- **POP3/IMAP**: Receiving email.
- **DNS**: Domain Name System (Port 53) - Maps names to IPs.
- **DHCP**: Dynamic Host Configuration Protocol - Assigns IPs automatically.
- **ARP**: Address Resolution Protocol - Maps IP to MAC address.
`
  },
  {
    id: 'dbms-notes',
    title: 'DBMS - Quick Recap',
    topic: 'DBMS',
    content: `
# DBMS - Quick Recap

## ACID Properties (Transaction Management)
1. **Atomicity**: All or nothing. (Commit/Rollback).
2. **Consistency**: Database remains in a consistent state before and after transaction.
3. **Isolation**: Transactions occur independently without interference.
4. **Durability**: Committed data is saved permanently, even after power loss.

## Normalization
**Goal**: Reduce redundancy and dependency.
- **1NF**: Atomic values (no repeating groups).
- **2NF**: 1NF + No partial dependency (all non-key attributes depend on whole primary key).
- **3NF**: 2NF + No transitive dependency (A -> B -> C).
- **BCNF**: 3NF + For every dependency X -> Y, X must be a super key.

## SQL Commands
- **DDL** (Definition): CREATE, ALTER, DROP, TRUNCATE.
- **DML** (Manipulation): SELECT, INSERT, UPDATE, DELETE.
- **DCL** (Control): GRANT, REVOKE.
- **TCL** (Transaction): COMMIT, ROLLBACK, SAVEPOINT.

## Indexing
- **B-Tree / B+ Tree**: Standard indexing structure for range queries.
- **Clustered Index**: Sorts the actual data rows (only one per table).
- **Non-Clustered Index**: Separate structure pointing to data (multiple allowed).

## Keys
- **Primary Key**: Unique + Not Null.
- **Candidate Key**: A minimal super key.
- **Foreign Key**: References a Primary Key in another table (Referential Integrity).
- **Super Key**: Any set of attributes that uniquely identifies a row.
`
  },
  {
    id: 'dsa-arrays',
    title: 'Arrays & Strings - Complete Guide',
    topic: 'Data Structures',
    content: `
# Arrays & Strings - Complete Guide

## 1. Introduction to Arrays
An array is a collection of items stored at **contiguous memory locations**. The idea is to store multiple items of the same type together.

### Time Complexity
| Operation | Complexity | Description |
|-----------|------------|-------------|
| Access    | O(1)       | Random access via index |
| Search    | O(n)       | Linear search (unsorted) |
| Search    | O(log n)   | Binary search (sorted) |
| Insertion | O(n)       | Shifting elements required |
| Deletion  | O(n)       | Shifting elements required |

### Static vs Dynamic Arrays
- **Static (Fixed size)**: Size defined at compile time (e.g., \`int arr[10]\` in C++).
- **Dynamic (Resizing)**: Resizes automatically (e.g., \`vector\` in C++, \`ArrayList\` in Java, \`list\` in Python).
  - *Amortized O(1)* insertion: When full, it doubles size and copies elements.

---

## 2. Two Pointer Technique
A pattern where two pointers iterate through the data structure in tandem until one or both satisfy a condition.
**Usage**:
- **Opposite Ends**: Find pair with target sum in sorted array.
  - Left starts at 0, Right at n-1.
  - If sum < target, Left++. If sum > target, Right--.
- **Same Direction (Slow/Fast)**: Remove duplicates, detect cycles.

## 3. Sliding Window
Used for finding subarrays satisfying a condition (e.g., "Longest substring with k distinct chars").
**Logic**:
1. Expand \`right\` pointer to include elements.
2. If condition broken, shrink \`left\` pointer until valid.
3. Update result (max length, min length, etc.).

## 4. Prefix Sum
Precompute sums to answer range queries in O(1).
- \`P[i] = A[0] + A[1] + ... + A[i]\`
- Sum of \`A[L...R] = P[R] - P[L-1]\`

---

## 5. String Manipulation
Strings are arrays of characters.
- **Mutability**: 
  - Mutable: C++ \`std::string\`, Java \`StringBuilder\`.
  - Immutable: Java \`String\`, Python \`str\`.
- **Techniques**:
  - **Reverse**: Swap characters (Two pointers).
  - **Palindrome Check**: Compare start/end moving inwards.
  - **Anagrams**: Count character frequencies or sort and compare.
`
  },
  {
    id: 'dsa-linked-list',
    title: 'Linked Lists - Complete Guide',
    topic: 'Data Structures',
    content: `
# Linked Lists - Complete Guide

## 1. Introduction
A linear data structure where elements are not stored in contiguous locations. Elements are linked using pointers.

### Types
1. **Singly Linked List**: Each node points to the next. \`[Data|Next] -> [Data|Next] -> NULL\`
2. **Doubly Linked List**: Points to next and previous. \`NULL <- [Prev|Data|Next] <-> [Prev|Data|Next] -> NULL\`
3. **Circular Linked List**: Last node points to first.

### Complexity Comparison
| Operation | Array | Linked List |
|-----------|-------|-------------|
| Access    | O(1)  | O(n)        |
| Insert (Start) | O(n) | O(1)   |
| Insert (End)   | O(1)* | O(1) (with tail pointer) |
| Delete    | O(n)  | O(1) (if node known) |

---

## 2. Common Operations

### Reversal (Iterative)
\`\`\`python
prev = None
current = head
while current:
    next_node = current.next
    current.next = prev
    prev = current
    current = next_node
return prev
\`\`\`

### Cycle Detection (Floyd's Cycle Finding - Tortoise & Hare)
- Use two pointers: \`slow\` (move 1 step) and \`fast\` (move 2 steps).
- If they meet, there is a cycle.
- If \`fast\` reaches NULL, no cycle.

### Merge Two Sorted Lists
- Use a dummy node.
- Compare heads of both lists, attach smaller node to current, advance.
- Attach remaining part of non-empty list.

## 3. Advanced Concepts
- **Middle Element**: Slow/Fast pointers. When fast reaches end, slow is at middle.
- **Palindrome Check**: Find middle, reverse second half, compare both halves.
- **LRU Cache**: Implemented using Hash Map + Doubly Linked List (O(1) get/put).
`
  },
  {
    id: 'dsa-trees',
    title: 'Trees & BST - Complete Guide',
    topic: 'Data Structures',
    content: `
# Trees & Graphs - Data Structures

## 1. Binary Trees
A tree where every node has at most 2 children (Left, Right).

### Traversals (DFS)
1. **In-Order** (Left, Root, Right): Returns sorted values for BST.
2. **Pre-Order** (Root, Left, Right): Useful for cloning.
3. **Post-Order** (Left, Right, Root): Useful for deletion/evaluation.

### Level Order Traversal (BFS)
- Uses a **Queue**.
- Push root. While queue not empty: pop node, process, push children.

---

## 2. Binary Search Tree (BST)
- **Property**: Left subtree values < Root < Right subtree values.
- **Search/Insert/Delete**: O(log n) on average (O(h)).
- **Worst Case**: O(n) if skewed (like a line).

### Validation
To check if a tree is a valid BST:
- **Range Approach**: Pass \`(min, max)\` range down.
- \`validate(node, min, max)\`:
  - if \`node.val <= min\` or \`node.val >= max\`: return false.
  - return \`validate(left, min, node.val) && validate(right, node.val, max)\`.

---

## 3. Balanced Trees
To guarantee O(log n), trees stay balanced (Height ≈ log N).
- **AVL Trees**: Self-balancing BST where difference between heights of subtrees is <= 1.
- **Red-Black Trees**: Used in Java \`TreeMap\`, C++ \`map\`.

## 4. Heaps (Priority Queue)
- **Min-Heap**: Parent <= Children. Root is minimum.
- **Max-Heap**: Parent >= Children. Root is maximum.
- **Representation**: Array. Parent at \`i\`, children at \`2i+1\`, \`2i+2\`.
- **Insert/Extract**: O(log n).
- **Peek**: O(1).
`
  },
  {
    id: 'dsa-graphs',
    title: 'Graph Algorithms - Complete Guide',
    topic: 'Algorithms',
    content: `
# Graphs - Algorithms & Traversal

## 1. Representations
1. **Adjacency Matrix**: 2D array \`adj[i][j] = 1\` if connected.
   - Space: O(V²). Good for dense graphs. O(1) edge check.
2. **Adjacency List**: Array of Lists/Vectors. \`adj[i] = [neighbor1, neighbor3]\`.
   - Space: O(V+E). Good for sparse graphs.

---

## 2. Traversals

### BFS (Breadth-First Search)
- Uses **Queue**.
- Explores neighbors layer by layer.
- **Use Case**: Shortest Path in unweighted graph.

### DFS (Depth-First Search)
- Uses **Stack** (or Recursion).
- Goes deep into one path, then backtracks.
- **Use Case**: Cycle detection, Topological sort, Connectivity.

---

## 3. Important Algorithms

### Topological Sort (DAG only)
- Linear ordering where for every edge u->v, u comes before v.
- **Kahn's Algorithm** (BFS with in-degrees) or **DFS approach**.
- **Application**: Task scheduling, build systems.

### Dijkstra's Algorithm (Shortest Path)
- Weighted graphs (non-negative weights).
- Uses **Priority Queue** (Min-Heap).
- Greedily picks closest unvisited node.
- Complexity: O(E log V).

### Bellman-Ford
- Handles negative weights (and detects negative cycles).
- Relax all edges V-1 times.
- Complexity: O(VE).

### Prim's & Kruskal's (MST)
- Find Minimum Spanning Tree (connect all nodes with min total weight, no cycles).
- **Prim**: Greedy builds from a node (like Dijkstra).
- **Kruskal**: Greedy adds edges (Union-Find).
`
  },
  {
    id: 'dsa-dp',
    title: 'Dynamic Programming - Complete Guide',
    topic: 'Algorithms',
    content: `
# Dynamic Programming (DP)

## 1. What is DP?
Optimization method for problems with:
1. **Overlapping Subproblems**: Same subproblems solved repeatedly.
2. **Optimal Substructure**: Optimal solution built from optimal sub-solutions.

### Approaches
- **Memoization (Top-Down)**: Recursion + Caching.
  - Pros: Easy to write, solves only needed states.
  - Cons: Stack overflow risk.
- **Tabulation (Bottom-Up)**: Iterative + Table filling.
  - Pros: No recursion overhead, memory optimization possible.

---

## 2. Common Patterns

### 1. 0/1 Knapsack Pattern
- Items have weight and value. Max value within capacity W?
- Choice: Include item or Exclude item.
- \`dp[i][w] = max(val[i] + dp[i-1][w-wt[i]], dp[i-1][w])\`

### 2. Unbounded Knapsack
- Items can be managed infinite times (e.g., Coin Change).
- \`dp[w] = min(dp[w], dp[w-coin] + 1)\`

### 3. Longest Common Subsequence (LCS)
- Strings A and B.
- If \`A[i] == B[j]\`: \`1 + LCS(i-1, j-1)\`
- Else: \`max(LCS(i-1, j), LCS(i, j-1))\`

### 4. Longest Increasing Subsequence (LIS)
- \`dp[i] = 1 + max(dp[j])\` for all \`j < i\` where \`arr[j] < arr[i]\`.
- O(n²) standard, O(n log n) with binary search.

### 5. Matrix Chain Multiplication (MCM)
- Partitioning problems (e.g., Palindrome Partitioning).
- Iterate split point \`k\` from \`i\` to \`j\`.
`
  },
  {
    id: 'dsa-stack-queue',
    title: 'Stacks & Queues - Complete Guide',
    topic: 'Data Structures',
    content: `
# Stacks & Queues

## 1. Stack (LIFO - Last In First Out)
Think of a stack of plates. You put one on top (push) and take from top (pop).

### Operations
- **Push**: Add to top. O(1).
- **Pop**: Remove from top. O(1).
- **Peek/Top**: View top element. O(1).
- **isEmpty**: Check if empty. O(1).

### Applications
- **Function Call Stack**: Stores local variables and return addresses.
- **Undo/Redo**: Editors stores states in stack.
- **Bracket Matching**: Validating \`((a+b))\`.
- **Expression Evaluation**: Infix to Postfix conversion.

---

## 2. Queue (FIFO - First In First Out)
Think of a line at a ticket counter. First person arrives, first person served.

### Operations
- **Enqueue**: Add to rear. O(1).
- **Dequeue**: Remove from front. O(1).
- **Front/Peek**: View first element. O(1).

### Applications
- **CPU Scheduling**: FCFS algorithm.
- **Print Spooling**: Documents processed in order.
- **BFS**: Graph traversal logic.

### Priority Queue (Heap)
- Elements processed based on priority, not arrival order.
- Insert/Delete: O(log n).
`
  },
  {
    id: 'dsa-sorting',
    title: 'Sorting Algorithms - Complete Guide',
    topic: 'Algorithms',
    content: `
# Sorting Algorithms

## 1. O(n²) Algorithms (Quadratic)
Good for small datasets only.
1. **Bubble Sort**: Repeatedly swap adjacent elements if wrong order.
   - Stable, In-place.
2. **Insertion Sort**: Build sorted array one by one.
   - Good for nearly sorted data. Stable, In-place.
3. **Selection Sort**: Find min element and swap to correct position.
   - Unstable, In-place.

---

## 2. O(n log n) Algorithms (Log-Linear)
Standard for general purpose sorting.
1. **Merge Sort**: Divide and Conquer. Split array, sort halves, merge.
   - **Stable**: Yes.
   - **Space**: O(n).
   - **Good for**: Linked Lists.

2. **Quick Sort**: Divide and Conquer using pivot. Partition array around pivot.
   - **Stable**: No.
   - **Space**: O(log n) stack.
   - **Worst Case**: O(n²) if pivot bad.
   - **Good for**: Arrays (cache friendly).

3. **Heap Sort**: Use Binary Heap.
   - **Stable**: No.
   - **Space**: O(1).

---

## 3. Special Sorts
1. **Counting Sort**: O(n+k). For integers with small range.
2. **Radix Sort**: O(nk). Digit by digit sorting.
`
  },
  {
    id: 'dsa-searching',
    title: 'Searching Algorithms - Complete Guide',
    topic: 'Algorithms',
    content: `
# Searching Algorithms

## 1. Linear Search
- **Method**: Check every element one by one.
- **Complexity**: O(n).
- **Pre-condition**: None (works on unsorted).

## 2. Binary Search
- **Method**: Divide search space in half repeatedly.
- **Complexity**: O(log n).
- **Pre-condition**: Array **MUST** be sorted.

### Algorithm
\`\`\`python
low = 0
high = n - 1
while low <= high:
    mid = (low + high) // 2
    if arr[mid] == target:
        return mid
    elif arr[mid] < target:
        low = mid + 1
    else:
        high = mid - 1
return -1
\`\`\`

### Variations
1. **Lower Bound**: First value >= target.
2. **Upper Bound**: First value > target.
3. **Rotated Array**: Find pivot then binary search.
`
  }
];

export function getNoteById(id: string) {
  return offlineNotes.find(n => n.id === id);
}
