// AUTO-GENERATED: Scraped content from external sources
// Generated on: 2026-01-18T22:12:46.433Z

export const scrapedProblems = {
  "LeetCode Top Interview 150": [
    "Must-do List for Interview Prep",
    "Top Interview 150",
    "Show tags",
    "Merge Sorted Array",
    "Remove Element",
    "Remove Duplicates from Sorted Array",
    "Remove Duplicates from Sorted Array II",
    "Majority Element",
    "Rotate Array",
    "Best Time to Buy and Sell Stock",
    "Best Time to Buy and Sell Stock II",
    "Jump Game",
    "Jump Game II",
    "H-Index",
    "Insert Delete GetRandom O(1)",
    "Product of Array Except Self",
    "Gas Station",
    "Candy",
    "Trapping Rain Water",
    "Roman to Integer",
    "Integer to Roman",
    "Length of Last Word",
    "Longest Common Prefix",
    "Reverse Words in a String",
    "Zigzag Conversion",
    "Find the Index of the First Occurrence in a String",
    "Text Justification",
    "Valid Palindrome",
    "Is Subsequence",
    "Two Sum II - Input Array Is Sorted",
    "Container With Most Water",
    "3Sum",
    "Minimum Size Subarray Sum",
    "Longest Substring Without Repeating Characters",
    "Substring with Concatenation of All Words",
    "Minimum Window Substring",
    "Valid Sudoku",
    "Spiral Matrix",
    "Rotate Image",
    "Set Matrix Zeroes",
    "Game of Life",
    "Ransom Note",
    "Isomorphic Strings",
    "Word Pattern",
    "Valid Anagram",
    "Group Anagrams",
    "Two Sum",
    "Happy Number",
    "Contains Duplicate II",
    "Longest Consecutive Sequence",
    "Summary Ranges",
    "Merge Intervals",
    "Insert Interval",
    "Minimum Number of Arrows to Burst Balloons",
    "Valid Parentheses",
    "Simplify Path",
    "Min Stack",
    "Evaluate Reverse Polish Notation",
    "Basic Calculator",
    "Linked List Cycle",
    "Add Two Numbers",
    "Merge Two Sorted Lists",
    "Copy List with Random Pointer",
    "Reverse Linked List II",
    "Reverse Nodes in k-Group",
    "Remove Nth Node From End of List",
    "Remove Duplicates from Sorted List II",
    "Rotate List",
    "Partition List",
    "LRU Cache",
    "Maximum Depth of Binary Tree",
    "Same Tree",
    "Invert Binary Tree",
    "Symmetric Tree",
    "Construct Binary Tree from Preorder and Inorder Traversal",
    "Construct Binary Tree from Inorder and Postorder Traversal",
    "Populating Next Right Pointers in Each Node II",
    "Flatten Binary Tree to Linked List",
    "Path Sum",
    "Sum Root to Leaf Numbers",
    "Binary Tree Maximum Path Sum",
    "Binary Search Tree Iterator",
    "Count Complete Tree Nodes",
    "Lowest Common Ancestor of a Binary Tree",
    "Binary Tree Right Side View",
    "Average of Levels in Binary Tree",
    "Binary Tree Level Order Traversal",
    "Binary Tree Zigzag Level Order Traversal",
    "Minimum Absolute Difference in BST",
    "Kth Smallest Element in a BST",
    "Validate Binary Search Tree",
    "Number of Islands",
    "Surrounded Regions",
    "Clone Graph",
    "Evaluate Division",
    "Course Schedule",
    "Course Schedule II",
    "Snakes and Ladders",
    "Minimum Genetic Mutation",
    "Word Ladder",
  ],
  "LeetCode Top SQL 50": [
    "Crack SQL Interview in 50 Qs",
    "SQL 50",
    "Show tags",
    "Recyclable and Low Fat Products",
    "Find Customer Referee",
    "Big Countries",
    "Article Views I",
    "Invalid Tweets",
    "Replace Employee ID With The Unique Identifier",
    "Product Sales Analysis I",
    "Customer Who Visited but Did Not Make Any Transactions",
    "Rising Temperature",
    "Average Time of Process per Machine",
    "Employee Bonus",
    "Students and Examinations",
    "Managers with at Least 5 Direct Reports",
    "Confirmation Rate",
    "Not Boring Movies",
    "Average Selling Price",
    "Project Employees I",
    "Percentage of Users Attended a Contest",
    "Queries Quality and Percentage",
    "Monthly Transactions I",
    "Immediate Food Delivery II",
    "Game Play Analysis IV",
    "Number of Unique Subjects Taught by Each Teacher",
    "User Activity for the Past 30 Days I",
    "Product Sales Analysis III",
    "Classes With at Least 5 Students",
    "Find Followers Count",
    "Biggest Single Number",
    "Customers Who Bought All Products",
    "The Number of Employees Which Report to Each Employee",
    "Primary Department for Each Employee",
    "Triangle Judgement",
    "Consecutive Numbers",
    "Product Price at a Given Date",
    "Last Person to Fit in the Bus",
    "Count Salary Categories",
    "Employees Whose Manager Left the Company",
    "Exchange Seats",
    "Movie Rating",
    "Restaurant Growth",
    "Friend Requests II: Who Has the Most Friends",
    "Investments in 2016",
    "Department Top Three Salaries",
    "Fix Names in a Table",
    "Patients With a Condition",
    "Delete Duplicate Emails",
    "Second Highest Salary",
    "Group Sold Products By The Date",
    "List the Products Ordered in a Period",
    "Find Users With Valid E-Mails",
    "SQL 50",
    "Advanced SQL 50",
    "50 Advanced SQL Problems",
    "Vbarkade700",
    "Pabitha_S",
    "DhanvandhiniL",
    "vnirmal9",
    "Owais",
  ],
  "Naukri TCS Aptitude": [
    "Get Career-Ready with Naukri Campus",
    "TCS Aptitude Questions PDF – Solved",
    "TCS Aptitude Test: Understanding the Structure",
    "TCS Aptitude Questions: TCS NQT Previous Year Questions",
    "TCS NQT Aptitude Test with Descriptive Answers",
    "Firstnaukri Aptitude Tests: Your Ultimate Preparation Partner",
    "How to Become a Counselling Psychologist in India After 12th",
    "Highest Paying Sales Jobs in India – Salaries, Skills, Roles",
    "ACCA vs CFA: Which is Better?",
    "Game Developer: The Ultimate 2025 Guide for Students & Freshers",
    "BCom Honours Salary in India: Freshers to Experienced",
    "How to Write Mail for Job Application – Explained",
    "250+ Group Discussion Topics for Interviews with Expert GD Tips",
    "Latest Mechanical Engineering Interview Questions and Answers",
    "Lessons from My Full Stack Development Internship Journey",
    "Latest Basic Electronics Interview Questions and Answers",
    "Was this post helpful?",
  ],
};

export const scrapedSources = ["LeetCode Top Interview 150","LeetCode Top SQL 50","CodeChef TCS Interview","Naukri TCS Aptitude","IndiaBix Logical Reasoning"];
